# LAB 1A - Variables and String Operations

# Aim: Write a python program on types, Expressions, Variables data types.

### 1.Question: swapping two numbers without using third variable

In [10]:
# Program:
a = int(input())
b = int(input())
print("Before Swapping",a,b)
a,b = b,a
print("After Swapping",a,b)

 10
 20

Before Swapping 10 20
After Swapping 20 10

### 2.Question: Write a python program that asks user name and age and returns the year which he gets 100 years

In [1]:
#program
userName = input("Enter User Name: ")
age = int(input("Enter age"))
print(userName,"will be 100 years old in" ,2025 + (100 - age))

Enter User Name:  Jyoshna
Enter age 19

Jyoshna will be 100 years old in 2106

### 3.Question: Given the output of the following when num1=4, num2 = 3, num3=2

In [22]:
#Program:
num1 = 4
num2 = 3
num3 = 2
#i
num1+= num2 + num3
print(num1)
#ii
num1 = 4
num1 =num1**(num2+num3)
print(num1)
#iii
num1 = 4
num1**= num2+num3
print(num1)
#iv
num1 = '5'+'5'
print(num1)
#v
print(10+6*2**2 != 9//4-3 and 29 >= 29/9)
#vi
print(5%19 + 10 < 50 and 29 <= 29)

9
1024
1024
55
True
True

### 4.Question: write a python program to read input string from the user and dispay the first and last characters.

In [33]:
#Program:
s = input()
print("First Character:",s[0])
print("Last Character:",s[-1])

 Hello World

First Character: H
Last Character: d

### 5.Question: Write a python program to read input from the user and display the string n times

In [42]:
#Program:
s = input("Enter String: ")
n = int(input("Enter n: "))
print((s+" ")*n)

Enter String:  hello
Enter n:  5

hello hello hello hello hello

### 6.Question: Write a python program to read input string from the user and display it in reverse order without creating a new string

In [53]:
#Program:
s = input()
print("Reverse String is: ",s[::-1])

 Hello World

Reverse String is:  dlroW olleH

### 7.Question: write a python program to input lines of text from the user until enter is pressed, count the total number of characters in the text including whitespaces, total number of alphabets, digits and special symbols and total number of words in the given text.

In [2]:
s = input()
c,d,sp = 0,0,0
for i in s:
    if i.isdigit():
        d += 1
    elif i.isalpha():
        c += 1
    else:
        sp += 1
print("Total no.of Charcters:",len(s))
print("Total no.of Alphabets:",c)
print("Total no.of digits:",d)
print("Total no.of Special Charcters:",sp)
print("Total no.of Words:",len(s.split()))

 jhgfdtyuiknbjkl;'

Total no.of Charcters: 17
Total no.of Alphabets: 15
Total no.of digits: 0
Total no.of Special Charcters: 2
Total no.of Words: 1

# LAB 1B

## Aim: To Write python program on lists, tuples, sets, dictionaris

## Lists

## 2.Quetion: Write a python program to check if a number is present in list or not. If yes print position else print an appropriate message

In [75]:
#Program:
l = list(map(int,input("Enter list:").split()))
k = int(input("Enter Number"))
for i in range(len(l)):
    if l[i] == k:
        print("Number is at index:",i)
        break
else:
    print("Number is not Present in the List!")

Enter list: 10 20 30 40 50
Enter Number 30

Number is at index: 2

### 3.Question: Write a python program to read list of integers (+ve and -ve). Create 2 new lists, one having all +ve num, another having all -ve numbers fromthe given list print all lists.

In [78]:
l = list(map(int,input("Enter list:").split()))
p = []
n = []
for i in l:
    if i >= 0:
        p.append(i)
    else:
        n.append(i)
print("Positive Numbers List:",p)
print("Negative Numbers List:",n)

Enter list: -2 3 9 6 10 -3 -5 -7 -10 -20 45 60 -100

Positive Numbers List: [3, 9, 6, 10, 45, 60]
Negative Numbers List: [-2, -3, -5, -7, -10, -20, -100]

## Tuples

### 1.Question write a python program to read email id of n students and store it in a tuple, create two new tuples, one stores only usernames from email id and one stores domain names from email id. print all the tuples at in the end of the program

In [3]:
#Program:
n = int(input("Enter n:"))
t = tuple()
for i in range(n):
    e = input()
    t += (e,)

userNames = tuple()
DomainNames = tuple()
for email in t:
    l = email.split("@")
    userNames += (l[0],)
    DomainNames += (l[1],)
print(t)
print("User Names Tuples:",userNames)
print("Domain Names Tuple:",DomainNames)

Enter n: 3
 jyosh@gmail.com
 kammu@gmail.com
 blabla@gmail.com

('jyosh@gmail.com', 'kammu@gmail.com', 'blabla@gmail.com')
User Names Tuples: ('jyosh', 'kammu', 'blabla')
Domain Names Tuple: ('gmail.com', 'gmail.com', 'gmail.com')

### 2.Question: write a python program to input names of n student and store them in tuple also input a name from the user and find if student is present in the tuple or not

In [4]:
n = int(input("Enter n:"))
t = tuple()
for i in range(n):
    name = input()
    t += (name,)
print(t)
find = input("Enter Name:")
print("Name is in tuple:",find in t)

Enter n: 2
 jyo
 jyosh

('jyo', 'jyosh')

Enter Name: jyo

Name is in tuple: True

## Sets

### 1.Question: Write a python program to create set of courses offered by RGUKT and display the no of courses available and ask a branch from the user and check whether it is vaild or not

In [10]:
#Program:
courses = set()
courses.add("CSE")
courses.add("ECE")
courses.add("EEE")
courses.add("MME")
courses.add("MECH")
courses.add("CH")
courses.add("CIVIL")
print("No.of Courses Available:", len(courses), courses)
b = input("Enter Branch")
if b in courses:
    print(b,"is a Valid Course")
else:
    print(b,"is a InValid Course")

No.of Courses Available: 7 {'CH', 'MECH', 'CSE', 'ECE', 'MME', 'CIVIL', 'EEE'}

Enter Branch CSE

CSE is a Valid Course

### 2.Question: Write a python program to create 2 sets with 1st 5 odd numbers and with first 5 even numbers and merge them

In [14]:
#Program:
odd = {x for x in range(1,10,2)}
even = {x for x in range(0,10,2)}
print("odd numbers Set:",odd)
print("Even numbers Set:",even)
nums = even.union(odd)
print(nums)

odd numbers Set: {1, 3, 5, 7, 9}
Even numbers Set: {0, 2, 4, 6, 8}
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

## Dictionaries

### 1.Question: Write a python program to enter names of employers and salaries as the input and store them in dictionary

In [5]:
#Program:
n = int(input("Enter no.of Employees:"))
employees = dict()
for i in range(n):
    name = input("Enter Employee Name:")
    salary = int(input("Enter Employee salary:"))
    employees[name] = salary
print("Employees Dictionary",employees)

Enter no.of Employees: 2
Enter Employee Name: jyo
Enter Employee salary: 2000000
Enter Employee Name: jyoshh
Enter Employee salary: 4000000

Employees Dictionary {'jyo': 2000000, 'jyoshh': 4000000}

### 2.Question: Write a python program to convert a number entered by user into a corresponding number in words

In [16]:
n = int(input("Enter Number:"))
#crores,lakhs,thousand,hundred
#Program
word = { 0:"",1:'one', 2:'two', 3:'three', 4:'four', 5:'five', 6:'six', 7:'seven', 8:'eight',
         9:'nine', 10:'ten', 11:'eleven', 12:'twelve', 13:'thirteen', 14:'forteen',
         15:'fifteen', 16:'sixteen', 17:'seventeen', 18:'eighteen', 19:'nineteen',
         20:'twenty', 30:'thirty', 40:'forty', 50:'fifty', 60:'sixty', 70:'seventy',
         80:'eighty', 90:'ninety'
        }
output = []
num = n
def spellTwo(n,tens):
    if(word.get(tens,-1) == -1):
            t = tens - n%10
            output.insert(0,word.get(n%10))
            output.insert(0,word.get(t))
    else:
        output.insert(0,word.get(tens))
while(n > 0):
    tens = n%100
    if(tens > 0):
        spellTwo(n,tens)
        output.insert(0,'and')
    n //= 100
    hun = n%10
    if(hun > 0):
        output.insert(0,'hundred')
        output.insert(0,word.get(hun))
    n //= 10
    thou = n%100
    if(thou > 0):
        output.insert(0,'thousand')
        spellTwo(n,thou)
    n //= 100
    lakh = n%100
    if(lakh > 0):
        output.insert(0,'lakh')
        spellTwo(n,lakh)
    n //= 100
    if(n > 0):
        output.insert(0,'crore')
# print(output)
print(num)
" ".join(output)

Enter Number: 9652501920

9652501920

'nine hundred and sixty five crore twenty five lakh one thousand nine hundred and twenty'

# 1C

## Conditional Statements

### 1.Question: write a python to display appropriate message as per color if signal at road crossing

In [9]:
#Program:
color = input("Enter color:").lower()
if color == 'red':
    print("Please Stop! The signal is red.")
elif color == 'yellow':
    print("Caution! The signal is yellow.")
elif color == 'green':
    print("Go! The signal is green.")
else:
    print("Invalid color! Please enter red, yellow, or green.")

Enter color: red

Please Stop! The signal is red.

### 2.Question: write a python program to create a simple calculator performing only four basic operations '+', '-', '*', '/'

In [21]:
#Program
print("Select operation:")
print("1. Add")
print("2. Subtract")
print("3. Multiply")
print("4. Divide")
choice = input("Enter choice (1/2/3/4): ")
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
if choice == '1':
    print(f"{num1} + {num2} = {num1 + num2}")
elif choice == '2':
    print(f"{num1} - {num2} = {num1 - num2}")
elif choice == '3':
    print(f"{num1} * {num2} = {num1 *num2}")
elif choice == '4':
    print(f"{num1} / {num2} = {num1 / num2}")
else:
    print("Invalid input")

Select operation:
1. Add
2. Subtract
3. Multiply
4. Divide

Enter choice (1/2/3/4):  4
Enter first number:  10
Enter second number:  2

10.0 / 2.0 = 5.0

### 3.Question: write a python program that takes name and age of user as input and display a message whether user is eligible for applying driver's license or not (18+ years are eligible)

In [6]:
name = input("Enter Name:")
age = int(input("Enter age:"))
if(age >= 18):
    print(name,"is Eligible for applying driver's license")
else:
    print(name,"is Not Eligible for applying driver's license")

Enter Name: jyosh
Enter age: 19

jyosh is Eligible for applying driver's license

### 4.Question: write a python program to check whether entered year is leap year or not

In [53]:
year = int(input("Enter Year:"))
if (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0):
    print(year,"is Leap year")
else:
    print(year,"is Not Leap year")

Enter Year: 2025

2025 is Not Leap year

## Loops

### 1.Question: write a python program to generate a seqence -5,10,-15,-25.....

In [2]:
#Program:
n = int(input("Enter n:"))
s = -1;
for i in range(5,n,5):
    print(i*s,end=", ")
    s *= -1
print("\b\b.")

Enter n: 50

-5, 10, -15, 20, -25, 30, -35, 40, -45.

### 2.Question: To print prime no;s b/w 2 and 50

In [105]:
import math
#progaram:
def prime(n):
    if n == 2: return True
    for i in range(2,math.ceil(math.sqrt(n))+1):
        if n%i == 0:
            return False
    return True
for i in range(2,50):
    if(prime(i)):
        print(i,end=", ")
print("\b\b.")

2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47.

### 3.Question: To Print factors of a whole number using while loop

In [131]:
n = int(input("Enter Number:"))
i = 1
while(i <= n):
    if(n%i == 0):
        print(i, end=", ")
    i+=1
print("\b\b.")

Enter Number: 96

1, 2, 3, 4, 6, 8, 12, 16, 24, 32, 48, 96.

### 4.Question: find sum of all possible integers entered by the user as soon as user enters a negative number stop taking further i/p from the user and display sum.

In [142]:
#program:
num = int(input("Enter Number:"))
sum = 0
while(num >= 0):
    sum += num
    num = int(input("Enter Number:"))
print("sum:",sum)

Enter Number: 65
Enter Number: 54
Enter Number: 54
Enter Number: 55
Enter Number: 87
Enter Number: 2
Enter Number: 871
Enter Number: -100000000000

sum: 1188

## Functions

In [28]:
def fibonacci(n):
    if(l[n] != None):
        return l[n]
    x,y = fibonacci(n-1), fibonacci(n-2)
    l[n] = x+y
    return x+y
n = int(input("Enter n: "))
l = [None]*(n+1)
l[0] = l[1] = 1
fibonacci(n)
l

Enter n:  10

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89]

In [30]:
def sum_first_n(n):
    return n*(n+1)/2
n = int(input("Enter n:"))
print("sum:",sum_first_n(n))

Enter n: 11

sum: 66.0

In [12]:
lis = list(map(float,input("Enter List: ").split(" ")))
def mean(l):
    s = 0
    for i in l:
        s += i
    return s/len(l)
print("mean of list:",mean(lis))

Enter List:  10.5 65.4 55.5 20.656

sum of list: 38.014

In [14]:
def power(base,exponent):
    return base**exponent
base = int(input("Enter Base:")) 
exponent = int(input("Enter Exponent:"))
print("Result:",power(base,exponent))

Enter Base: 10
Enter Exponent: 5

Result: 100000

In [7]:

#create a class called students with attributes name , id, branch , methods precentage, grade. display the above details id,name,brance,percentance,grade
#for at least two students
class student:
    def __init__(self,name, id , branch, marks):
        self.name = name
        self.id = id
        self.branch = branch
        self.marks = marks
    def percentage(self):
        return (self.marks/600)*100
    def grade(self):
        if(self.marks > 550):
            return "A"
        elif(self.marks > 500):
            return "B"
        elif(self.marks > 450):
            return "C"
        elif(self.marks > 400):
            return "D"
        else:
            return "F"
std1 = student("Jyosh",210903,"CSE",567)
print(std1.id, std1.name, std1.branch, std1.percentage(), std1.grade())

std2 = student("suji",210015,"CSE",499)
print(std2.id, std2.name,  std2.branch, std2.percentage(), std2.grade())

210903 Jyosh CSE 94.5 A
210015 suji CSE 83.16666666666667 C

In [32]:
class rgukt:
    def __init__(self, loc, strength,courses):
        self.loc = loc
        self.strength = strength
        self.courses = courses 
    def show_courses(self):
        print("Available Courses are:")
        for c in self.courses:
            print(c)
rkv = rgukt("Kadapa",10000,['CSE', 'MECH', 'CH',  'ECE', 'MME', 'CIVIL', 'EEE'])
nuzvid = rgukt("Nuzvid",8000,['CSE', 'MECH', 'CH', 'ECE', 'MME', 'CIVIL', 'EEE'])
print(rkv.loc, rkv.strength)
rkv.show_courses()

Kadapa 10000
Available Courses are:
CSE
MECH
CH
ECE
MME
CIVIL
EEE

                                    Files concepts

In [1]:
#opening , reading and writing data into a file
f=open("filem.txt","w+");
n=int(input("Enter no.of lines of text : "))
for i in range(n):
    data=input("Enter data")
    f.write(data)
print("The data you've written in the file");
f.seek(0,0)
print(f.read())

Enter no.of lines of text :  3
Enter data
Enter data hii
Enter data hello

The data you've written in the file
hiihello

In [2]:
f1=open("student.txt","w+");
f1.write("ID : S210651\n");
f1.write("Name : jyoshna\n");
f1.write("Roll No : 44\n");
f1.write("Branch : CSE\n");
f1.write("Year : E2\n");
f1.write("CGPA : 9.2\n");
f1.write("Address : West Godavari");
f1.seek(0,0)
print(f1.read())
f1.close()

ID : S210651
Name : jyoshna
Roll No : 44
Branch : CSE
Year : E2
CGPA : 9.2
Address : West Godavari

In [3]:
f2=open("num1c.txt","r")
for i in f2:
    print(i)
f2.close();

1

2

3

4

5

6

7

8

9

10

hello

hi

bye

how are you?

                                        NUMPY BASICS

In [ ]:
#create a 1D array called vowels having the elements "a","e","i","o","u"
#create a 1D array to store upto 1st 10 even numbers

In [8]:
import numpy as np

vowels = np.array(['a', 'e', 'i', 'o', 'u'])
print(vowels)

['a' 'e' 'i' 'o' 'u']

In [9]:

import numpy as np

even_numbers = np.arange(2, 21, 2)  # Generates even numbers from 2 to 20
print(even_numbers)

[ 2  4  6  8 10 12 14 16 18 20]

In [ ]:
#create 2D array called ones having 2 rows& 5 columns and all the elements are set to 1 and data type int
#use nested python lists to create a 2D array names myarray1 having 3 rows 3 columns and store the following [2.7,-2,-19,0,3.4,99.9,10.6,0,13]

In [16]:
import numpy as np

ones = np.ones((2, 5), dtype=int)
print(ones)

[[1 1 1 1 1]
 [1 1 1 1 1]]

In [19]:
import numpy as np
myarray1=np.array([2.7,-2,-19,0,3.4,99.9,10.6,0,13],dtype=float)
myarray1.reshape(3,3)

array([[  2.7,  -2. , -19. ],
       [  0. ,   3.4,  99.9],
       [ 10.6,   0. ,  13. ]])

In [ ]:
#create a 2D array called myarray2 using arrange() having 3 rows and 5 columns with start value=4,step size 4 and 4 and datatype as float

In [26]:
import numpy as np
myarray2=np.array([],dtype=float)
myarray2=np.arange(4,4+(3*5*4),4)
myarray2.reshape(3,5)

array([[ 4,  8, 12, 16, 20],
       [24, 28, 32, 36, 40],
       [44, 48, 52, 56, 60]])

In [ ]:
#4)

In [29]:
import numpy as np
myarray4=np.arange(-1,-1+(14*3*0.25),0.25 ).reshape(14,3)
myarray4

array([[-1.  , -0.75, -0.5 ],
       [-0.25,  0.  ,  0.25],
       [ 0.5 ,  0.75,  1.  ],
       [ 1.25,  1.5 ,  1.75],
       [ 2.  ,  2.25,  2.5 ],
       [ 2.75,  3.  ,  3.25],
       [ 3.5 ,  3.75,  4.  ],
       [ 4.25,  4.5 ,  4.75],
       [ 5.  ,  5.25,  5.5 ],
       [ 5.75,  6.  ,  6.25],
       [ 6.5 ,  6.75,  7.  ],
       [ 7.25,  7.5 ,  7.75],
       [ 8.  ,  8.25,  8.5 ],
       [ 8.75,  9.  ,  9.25]])

In [30]:
#5)

In [39]:
import numpy as np
arr=np.arange(1,1+(2*2*3),3).reshape(2,2)
s=arr.sum(axis=0)
print(arr)
print(s)

[[ 1  4]
 [ 7 10]]
[ 8 14]

In [ ]:
#6)

In [41]:
import numpy as np
arr=np.arange(1,1+(2*2*3),3).reshape(2,2)
s=arr.max()
print(arr)
print(s)

[[ 1  4]
 [ 7 10]]
10

In [ ]:
#7)

In [45]:
import numpy as np
arr=np.arange(1,1+(2*2*3),3).reshape(2,2)
s=arr.min(axis=1)
print(arr)
print(s)

[[ 1  4]
 [ 7 10]]
[1 7]

In [ ]:
#8)

In [46]:
import numpy as np
arr=np.arange(1,1+(2*2*3),3).reshape(2,2)
s=arr.mean(axis=1)
print(arr)
print(s)

[[ 1  4]
 [ 7 10]]
[2.5 8.5]

In [47]:
#9)

In [48]:
import numpy as np
arr=np.arange(1,1+(2*2*3),3).reshape(2,2)
s=arr.std(axis=0)
print(arr)
print(s)

[[ 1  4]
 [ 7 10]]
[3. 3.]

In [49]:
#10)

In [50]:
import numpy as np
arr=np.array([[1,3],[23,90]],dtype=float)
p=arr/3
p

array([[ 0.33333333,  1.        ],
       [ 7.66666667, 30.        ]])

In [ ]:
#11)

In [56]:
import numpy as np
arr1=np.array([[12,13,14],[4,5,6]])
arr2=np.array([[12,36,12],[12,3,2]])
s=arr1+arr2
s

array([[24, 49, 26],
       [16,  8,  8]])

In [ ]:
#12)

In [57]:
import numpy as np
arr1=np.array([[12,13,14],[4,5,6]])
arr2=np.array([[12,36,12],[12,3,2]])
s=arr2-arr1
p=np.array(s)
p

array([[ 0, 23, -2],
       [ 8, -2, -4]])

In [ ]:
#13)

In [58]:
import numpy as np
arr1=np.array([[12,13,14],[4,5,6]])
arr2=np.array([[12,36,12],[12,3,2]])
s=arr1*arr2
s

array([[144, 468, 168],
       [ 48,  15,  12]])

In [ ]:
#14)

In [59]:
import numpy as np
arr1=np.array([[12,13,14],[4,5,6]])
arr2=np.array([[12,36,12],[12,3,2]])
ar=arr2.transpose()
arr3=arr1@ar
arr3

array([[780, 211],
       [300,  75]])

                                                            PANDAS BASICS

In [ ]:
#Basic pandas importing using module
import pandas as pd
import numpy as np
a1=np.array([9,8,10,10,14,14,13])
a2=np.array([8,8,10,9,13,12,15])
a3=np.array([8,10,9,10,15,12,13])
a4=np.array([9,9,7,10,11,15,14])
a5=np.array([7,8,9,10,14,15,12])
d=pd.DataFrame([a1,a2,a3,a4,a5],columns=["AT1","AT2","AT3","AT4","Mid1","Mid2","Mid3"])
print(d)

In [4]:
#making a dataframe consisting of columns and index values
d2=pd.DataFrame([a1,a2,a3,a4,a5],columns=["AT1","AT2","AT3","AT4","Mid1","Mid2","Mid3"],index=["sub1","sub2","sub3","sub4","sub5"])
#retrieval of data from a dataframe
d2

      AT1  AT2  AT3  AT4  Mid1  Mid2  Mid3
sub1    9    8   10   10    14    14    13
sub2    8    8   10    9    13    12    15
sub3    8   10    9   10    15    12    13
sub4    9    9    7   10    11    15    14
sub5    7    8    9   10    14    15    12

In [5]:
#renaming the names of the columns
d3=d2.rename({"sub1":"DSP","sub2":"WT","sub4":"COA","sub5":"OR","sub3":"CD"})
print(d3)

     AT1  AT2  AT3  AT4  Mid1  Mid2  Mid3
DSP    9    8   10   10    14    14    13
WT     8    8   10    9    13    12    15
CD     8   10    9   10    15    12    13
COA    9    9    7   10    11    15    14
OR     7    8    9   10    14    15    12

In [6]:
#knowing the shape of a dataframe
d3.shape

(5, 7)

In [7]:
#retrieving the data from dataframe from head elements
d3.head()

     AT1  AT2  AT3  AT4  Mid1  Mid2  Mid3
DSP    9    8   10   10    14    14    13
WT     8    8   10    9    13    12    15
CD     8   10    9   10    15    12    13
COA    9    9    7   10    11    15    14
OR     7    8    9   10    14    15    12

In [8]:
#retrieving the top 3 rows from the dataframe
d3.head(3)

     AT1  AT2  AT3  AT4  Mid1  Mid2  Mid3
DSP    9    8   10   10    14    14    13
WT     8    8   10    9    13    12    15
CD     8   10    9   10    15    12    13

In [9]:
#retrieving the last row from the dataframe
d3.tail(1)

    AT1  AT2  AT3  AT4  Mid1  Mid2  Mid3
OR    7    8    9   10    14    15    12

In [11]:
#retrieving the data of IOR subject columns values
d5=d3.loc["OR"]
d5

AT1      7
AT2      8
AT3      9
AT4     10
Mid1    14
Mid2    15
Mid3    12
Name: OR, dtype: int64

In [12]:
#retrieving the data of WT subject columns values
d6=d3.loc["WT"]
d6

AT1      8
AT2      8
AT3     10
AT4      9
Mid1    13
Mid2    12
Mid3    15
Name: WT, dtype: int64

In [13]:
#adding both ior and wt column values
d5+d6

AT1     15
AT2     16
AT3     19
AT4     19
Mid1    27
Mid2    27
Mid3    27
dtype: int64

In [15]:
d7=d3.loc["WT"]+d3.loc["DSP"]
d7

AT1     17
AT2     16
AT3     20
AT4     19
Mid1    27
Mid2    26
Mid3    28
dtype: int64

In [17]:
#creation of series 
s2=pd.Series((10,9.9,8.5,9,8.8),index=["SSC","P1","P2","E1","E2"])
d8=pd.DataFrame(s2,columns=["CGPA"])
d8

     CGPA
SSC  10.0
P1    9.9
P2    8.5
E1    9.0
E2    8.8

In [19]:
ss=np.array(("SSC AP","Sri Chaitanya","2021","100"))
puc=np.array(("PUC","RGUKT SKLM","2023","96.7"))
bt=np.array(("BTECH CS","RGUKT sklm","2027","92.3"))
d10=pd.DataFrame([ss,puc,bt],columns=["Degree/Course","Institute","Year of Passing","Percentage"],index=["SSC","PUC","BTECH"])
d10

      Degree/Course      Institute Year of Passing Percentage
SSC          SSC AP  Sri Chaitanya            2021        100
PUC             PUC     RGUKT SKLM            2023       96.7
BTECH      BTECH CS     RGUKT sklm            2027       92.3

In [21]:
import pandas as pd
import numpy as np
a1=np.array([9,8,10,10,14,14,13])
a2=np.array([8,8,10,9,13,12,15])
a3=np.array([8,10,9,10,15,12,13])
a4=np.array([9,9,7,10,11,15,14])
a5=np.array([7,8,9,10,14,15,12])
d=pd.DataFrame([a1,a2,a3,a4,a5],columns=["AT1","AT2","AT3","AT4","Mid1","Mid2","Mid3"],index=["sub1","sub2","sub3","sub4","sub5"])
print(d)
#adding of a new row
d.loc["AI"]=[9,10,8,10,14,15,12]
print(d)

      AT1  AT2  AT3  AT4  Mid1  Mid2  Mid3
sub1    9    8   10   10    14    14    13
sub2    8    8   10    9    13    12    15
sub3    8   10    9   10    15    12    13
sub4    9    9    7   10    11    15    14
sub5    7    8    9   10    14    15    12
      AT1  AT2  AT3  AT4  Mid1  Mid2  Mid3
sub1    9    8   10   10    14    14    13
sub2    8    8   10    9    13    12    15
sub3    8   10    9   10    15    12    13
sub4    9    9    7   10    11    15    14
sub5    7    8    9   10    14    15    12
AI      9   10    8   10    14    15    12